# Generated by Django 2.2.4 on 2019-08-14 06:29

from django.db import migrations, models
import record.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('url', models.TextField(default=record.models.Category.url_default)),
            ],
        ),
    ]
