# Generated by Django 2.2.4 on 2019-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
