# Generated by Django 2.2.4 on 2019-08-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20190814_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='category',
            new_name='categories',
        ),
    ]
