# Generated by Django 2.2.4 on 2019-08-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20190814_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=15)),
                ('pushes', models.IntegerField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='category_of_article', to='record.Category')),
            ],
        ),
    ]
