# Generated by Django 2.2.4 on 2019-08-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
