# Generated by Django 2.2.4 on 2019-08-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20190814_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
