# Generated by Django 2.2.4 on 2019-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'date'), name='name of constraint'),
        ),
    ]
