# Generated by Django 2.2.4 on 2019-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20190814_1249'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='name of constraint'),
        ),
    ]
