# Generated by Django 2.2.4 on 2019-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_auto_20190814_1251'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'date'), name='name of constraint'),
        ),
    ]
